# Generated by Django 4.2 on 2026-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField(help_text='Soil moisture percentage (0-100)')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage (0-100)')),
                ('leaf_wetness', models.FloatField(help_text='Leaf wetness (0-1)')),
                ('ph_level', models.FloatField(help_text='Soil pH level')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('image_ndvi', models.FileField(blank=True, null=True, upload_to='ndvi_images/')),
                ('prediction_status', models.CharField(choices=[('healthy', 'Healthy'), ('stressed', 'Stressed')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence percentage (0-100)')),
                ('recommendation', models.TextField()),
                ('stress_reason', models.TextField(blank=True, null=True)),
                ('zone_map', models.JSONField(blank=True, default=list)),
                ('farm_name', models.CharField(blank=True, max_length=255)),
                ('farmer_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Crop Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
